name: Build and deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Rust (toolchain stable)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Upgrade pip and install wheel/build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: (Optional) Run tests
      run: |
        echo "No tests configured" || true

    - name: Install Node.js (for Netlify CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        # site id must be provided via secret NETLIFY_SITE_ID
        if [ -z "${{ secrets.NETLIFY_SITE_ID }}" ]; then echo "NETLIFY_SITE_ID secret is not set"; exit 1; fi
        netlify deploy --prod --dir=./ --site=${{ secrets.NETLIFY_SITE_ID }}

    
    